# Generated by Django 4.2 on 2025-06-08 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название объекта недвижимости', max_length=255, verbose_name='Название')),
                ('description', models.TextField(help_text='Опишите объект недвижимости', verbose_name='Описание')),
                ('deal_type', models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда')], help_text='Выберите тип сделки (Продажа или Аренда)', max_length=10, verbose_name='Тип сделки')),
                ('price', models.DecimalField(decimal_places=2, help_text='Укажите цену в долларах США', max_digits=10, verbose_name='Цена ($)')),
                ('rooms', models.IntegerField(choices=[(1, '1 комн.'), (2, '2 комн.'), (3, '3 комн.'), (4, '4 комн.'), (5, '5 комн.'), (6, '6 комн.'), (7, '7 комн.'), (8, '8 комн.'), (9, '9 комн.')], verbose_name='Количество комнат')),
                ('area', models.FloatField(help_text='Укажите площадь в квадратных метрах', verbose_name='Площадь (м²)')),
                ('address', models.CharField(help_text='Введите полный адрес объекта недвижимости', max_length=255, verbose_name='Адрес')),
                ('image1', models.ImageField(blank=True, help_text='Загрузите главное изображение объекта недвижимости', null=True, upload_to='properties/', verbose_name='Изображение 1')),
                ('image2', models.ImageField(blank=True, help_text='Загрузите дополнительное изображение объекта недвижимости', null=True, upload_to='properties/', verbose_name='Изображение 2')),
                ('image3', models.ImageField(blank=True, help_text='Загрузите еще одно дополнительное изображение объекта недвижимости', null=True, upload_to='properties/', verbose_name='Изображение 3')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания объявления', verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('buyer', 'Покупатель'), ('seller', 'Продавец')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='exam.property')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина удаления')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи заявки')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.property', verbose_name='Объявление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на удаление объявления',
                'verbose_name_plural': 'Заявки на удаление объявлений',
                'ordering': ['-created_at'],
            },
        ),
    ]
