# Generated by Django 4.2 on 2025-06-08 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo3',
        ),
        migrations.AddField(
            model_name='property',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина удаления')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи заявки')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.property', verbose_name='Объявление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
